name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the project
        run: |
          cd api-productos
          mvn clean package

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r * ec2-user@3.21.187.29:/home/ec2-user/app

      - name: Copy Docker Compose file to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ec2-user@3.21.187.29:/home/ec2-user/app/docker-compose.yml

      - name: SSH and deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.21.187.29 "cd /home/ec2-user/app && docker-compose up -d --build"

      
      - name: Close SSH connections (Optional)
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.21.187.29 "exit"
