name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ubuntu@54.210.233.63:/home/ubuntu/app

      - name: SSH and deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.210.233.63 "cd /home/ubuntu/app && docker-compose up -d --build"

