name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ec2-user@your-ec2-ip:/home/ec2-user/app

      - name: SSH and deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip "cd /home/ec2-user/app && docker-compose up -d --build"
